import path from "node:path";
import type { Project, Recipe, Route } from "../domain/types.js";
import { relativeAssetPrefix } from "../io/fs.js";
import { renderTemplate, resolveSectionContent } from "../renderer/template.js";

const themeInit =
  "(function(){var t=localStorage.getItem('draftpine-theme');if(!t)t=window.matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light';document.documentElement.dataset.theme=t;})();";

export function renderRouteHtml(project: Project, route: Route, recipe: Recipe): string {
  const content = project.content.get(route.id);
  const assetPrefix = relativeAssetPrefix(route.file);
  const depth = Math.max(0, route.file.split("/").filter(Boolean).length - 1);
  const sections = recipe.sections
    .filter((section) => section.visibility !== "hidden")
    .map((section) => {
      const primitive = project.registry.primitives.get(section.primitive);
      if (!primitive?.template) return "";
      const sectionContent = resolveSectionContent(section, content);
      return renderTemplate(primitive.template, {
        ...sectionContent,
        sectionId: section.id,
        primitive: section.primitive,
        layout: section.layout,
        variant: section.variant ?? "default"
      });
    })
    .join("\n");

  const description =
    typeof content?.description === "string"
      ? content.description
      : `${route.title} static Draftpine prototype for ${project.workspace.config.project.name}.`;

  const navLinks = project.routes
    .filter((item) => item.status !== "hidden" && item.status !== "deprecated")
    .map((item) => {
      const href = item.path === "/" ? assetPrefix : `${assetPrefix}${item.path.replace(/^\//, "")}`;
      return `<li><a href="${href}">${escapeText(item.title)}</a></li>`;
    })
    .join("");

  const themeToggle = project.workspace.config.theme.allowThemeToggle
    ? `<button type="button" class="dp-theme-toggle" data-draftpine-interaction="theme" aria-label="Toggle theme" @click="toggleTheme()"><span x-text="theme === 'dark' ? 'Light' : 'Dark'"></span></button>`
    : "";

  const bodyClass = `dp-route dp-route-${toClassName(route.routeType)} dp-route-id-${toClassName(route.id)}`;

  return `<!doctype html>
<html lang="en" x-data="{...createDraftpineShell({depth:${depth}})}" x-init="init()">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="color-scheme" content="light dark" />
    <title>${escapeText(route.title)} · ${escapeText(project.workspace.config.project.name)}</title>
    <meta name="description" content="${escapeText(description)}" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Geist:wght@400;500;600;700&display=swap" />
    <script>${themeInit}</script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css" />
    <link rel="stylesheet" href="${assetPrefix}assets/draftpine.css" />
  </head>
  <body class="${bodyClass}" data-route="${escapeText(route.id)}" data-route-type="${escapeText(route.routeType)}">
    <header class="dp-site-header">
      <nav class="dp-container">
        <ul><li><strong>${escapeText(project.workspace.config.project.name)}</strong></li></ul>
        <ul class="dp-site-nav-links" data-draftpine-overflow="allowed">${navLinks}<li>${themeToggle}</li></ul>
      </nav>
    </header>
    <main>
${sections}
    </main>
    <footer class="dp-site-footer">
      <div class="dp-container">
        <nav aria-label="Footer">
          <ul>${navLinks}</ul>
        </nav>
        <p>Generated by Draftpine.</p>
      </div>
    </footer>
    <script src="${assetPrefix}assets/draftpine.js"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
  </body>
</html>
`;
}

export function routeOutputPath(outputDir: string, route: Route): string {
  return path.join(outputDir, route.file);
}

function escapeText(value: unknown): string {
  return String(value ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

function toClassName(value: unknown): string {
  return String(value ?? "page")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "") || "page";
}
